spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  freemarker:
    template-loader-path: classpath:/templates/
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 8
    timeout: 200
  profiles:
    active: xshop-core
server:
  port: 8008


app:
  upload:
    shop:
      cover: /data/xuanhuobang/sites/xuanhuobang.com/www/cover_upload/
      pictures: /data/xuanhuobang/sites/xuanhuobang.com/www/pictures_upload/
    home:
      pictures: /data/xuanhuobang/sites/xuanhuobang.com/www/home_upload/
logging:
  path: /data/xuanhuobang_springboot/logs/
  level:
    root: info
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lhrsite.xshop.mapper
  # 打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
lombok:
  anyConstructor:
    addConstructorProperties: true