spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  freemarker:
    template-loader-path: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 8
    timeout: 200
  profiles:
    active: xshop-core
    include: xshop-dao
server:
  port: 8009
app:
  workspace: /Users/haoranliu/xshop/
  upload:
    rootDir: ${app.workspace}upload/
    shop:
      cover: ${app.upload.rootDir}cover_upload/
      pictures: ${app.upload.rootDir}pictures_upload/
    home:
      pictures: ${app.upload.rootDir}home_upload/
    classify:
      pictures: ${app.upload.rootDir}classify/
logging:
  path: ${app.workspace}/logs/
  level:
    root: info
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lhrsite.xshop.mapper
  # 打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
lombok:
  anyConstructor:
    addConstructorProperties: true
